FROM --platform=$BUILDPLATFORM jekyll/jekyll:3.8

COPY Gemfile /srv/jekyll
RUN bundle install 

COPY . /srv/jekyll/
RUN bundle exec jekyll build --config mains-config.yml

FROM --platform=$TARGETPLATFORM arm32v6/nginx:alpine
COPY nginx-config/nginx.conf /etc/nginx/nginx.conf
COPY nginx-config/jekyll.conf /etc/nginx/conf.d/jekyll.conf
COPY --from=0 /srv/jekyll/_site /usr/share/nginx/html
