FROM --platform=$BUILDPLATFORM jekyll/jekyll:3.8

COPY Gemfile /srv/jekyll
COPY Gemfile.lock /srv/jekyll
RUN bundle install --frozen

COPY . /srv/jekyll/
RUN bundle exec jekyll build --config solar-config.yml --trace

FROM --platform=$TARGETPLATFORM arm32v6/nginx:alpine
COPY nginx-config/nginx.conf /etc/nginx/nginx.conf
COPY nginx-config/jekyll.conf /etc/nginx/conf.d/jekyll.conf
COPY --from=0 /srv/jekyll/_site /usr/share/nginx/html
